[window]
startup_mode = "Maximized"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "/home/user/local/bin/prawjector start; exec zsh -l"]

##
## Github Dark High Contrast
## https://github.com/projekt0n/github-theme-contrib/blob/main/themes/alacritty/github_dark_high_contrast.yml
##
[colors]

[colors.primary]
background = '0x000000'
foreground = '0xf0f3f6'

[colors.cursor]
text = '0x0a0c10'
cursor = '0xf0f3f6'

[colors.normal]
black = '0x7a828e'
red = '0xff9492'
green = '0x26cd4d'
yellow = '0xf0b72f'
blue = '0x71b7ff'
magenta = '0xcb9eff'
cyan = '0x39c5cf'
white = '0xd9dee3'

[colors.bright]
black = '0x9ea7b3'
red = '0xffb1af'
green = '0x4ae168'
yellow = '0xf7c843'
blue = '0x91cbff'
magenta = '0xcb9eff'
cyan = '0x39c5cf'
white = '0xd9dee3'

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

