#!/bin/bash

npm install -g skills
skills add -g Shopify/shopify-ai-toolkit
skills add -g agent-browser
skills add -g clerk-cli
skills add -g find-docs
skills add -g playwright-cli
skills add -g clerk/skills
skills add -g neondatabase/agent-skills
skills add -g neondatabase/ai-rules
skills add -g vercel-labs/skills
skills add -g vercel-labs/agent-skills

