##
## General
##

model = "gpt-5.5"
model_verbosity = "medium"
model_reasoning_effort = "high"
personality = "pragmatic"
plan_mode_reasoning_effort = "high"
service_tier = "fast"

[features]
apps = false

[notice]
fast_default_opt_out = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[tui]
alternate_screen = "always"
model_availability_nux = { "gpt-5.5" = 4 }
session_picker_view = "comfortable"

##
## MCP Configs
##

[mcp_servers.chrome-devtools]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--autoConnect"]
tools.click = { approval_mode = "approve" }
tools.drag = { approval_mode = "approve" }
tools.emulate = { approval_mode = "approve" }
tools.evaluate_script = { approval_mode = "approve" }
tools.fill_form = { approval_mode = "approve" }
tools.navigate_page = { approval_mode = "approve" }
tools.new_page = { approval_mode = "approve" }
tools.press_key = { approval_mode = "approve" }
tools.resize_page = { approval_mode = "approve" }
tools.take_screenshot = { approval_mode = "approve" }
tools.take_snapshot = { approval_mode = "approve" }
enabled = true

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]
enabled = false

[mcp_servers.shopify-dev-mcp]
command = "npx"
args = ["-y", "@shopify/dev-mcp@latest"]
enabled = false

[mcp_servers.vercel]
url = "https://mcp.vercel.com"
enabled = false

##
## Paths
##

[projects."/home/user/foo"]
trust_level = "trusted"

